#!/bin/bash

# Compila pipex.c con libft.a
make

# Verifica si la compilación fue exitosa
if [ $? -eq 0 ]; then
    echo "Compilación CON banderas exitosa!"
    echo "./pipex infile "$1" "$2" outfile"
    echo '------------------------ '
    ./pipex infile "$1" "$2" outfile
    #rm pipex
else
    echo "Error: la compilación falló"
fi

#!/bin/bash

